before_script:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - git clone https://github.com/kana/vim-operator-user /tmp/vim-operator-user
  - git clone https://github.com/thinca/vim-themis --depth 1 /tmp/vim-themis

script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser plugin autoload
  - /tmp/vim-themis/bin/themis --runtimepath /tmp/vim-operator-user
  - echo 'set selection=exclusive' > test/.themisrc
  - /tmp/vim-themis/bin/themis --runtimepath /tmp/vim-operator-user
  - echo 'set selection=exclusive' > test/.themisrc
  - echo 'set virtualedit=block' >> test/.themisrc
  - /tmp/vim-themis/bin/themis --runtimepath /tmp/vim-operator-user
  - echo 'set selection=exclusive' > test/.themisrc
  - echo 'set virtualedit=insert' >> test/.themisrc
  - /tmp/vim-themis/bin/themis --runtimepath /tmp/vim-operator-user
# - echo 'set selection=exclusive' > test/.themisrc
# - echo 'set virtualedit=all' >> test/.themisrc
# - /tmp/vim-themis/bin/themis --runtimepath /tmp/vim-operator-user
  - echo 'set selection=exclusive' > test/.themisrc
  - echo 'set virtualedit=onemore' >> test/.themisrc
  - /tmp/vim-themis/bin/themis --runtimepath /tmp/vim-operator-user
  - echo 'set selection=old' > test/.themisrc
  - /tmp/vim-themis/bin/themis --runtimepath /tmp/vim-operator-user

